Repository gregoryjflaherty/little-esty-shop, pull requests merged in 2022-02, with the labels that each got.

#42 Setup
  Gemfile
  app/models/customer.rb
  app/models/invoice.rb
  app/models/invoice_item.rb
  app/models/item.rb
  app/models/merchant.rb
  app/models/transaction.rb
  db/schema.rb
  lib/tasks/csv_load.rake
  spec/models/customer_spec.rb
  spec/models/invoice_item_spec.rb
  spec/models/invoice_spec.rb
  spec/models/item_spec.rb
  spec/models/merchant_spec.rb
  spec/models/transaction_spec.rb
Labels: bug, documentation

#43 Feat: add shoulda_matchers to rails helper. 1 test not passing and fi…
  app/models/invoice_item.rb
  spec/models/customer_spec.rb
  spec/models/invoice_item_spec.rb
  spec/rails_helper.rb
Labels: bug, documentation

#45 DB: Create all migrations
  Gemfile.lock
  db/migrate/20220219164631_create_customers.rb
  db/migrate/20220219164714_create_invoices.rb
  db/migrate/20220219164734_create_merchants.rb
  db/migrate/20220219164746_create_items.rb
  db/migrate/20220219164758_create_invoice_items.rb
  db/migrate/20220219164818_create_transactions.rb
  db/schema.rb
Labels: enhancement

#46 Routes
  app/controllers/merchant_items_controller.rb
  app/controllers/merchants_controller.rb
  config/routes.rb
Labels: enhancement, question

#48 Test: Add spec files for all views
  spec/features/merchant_items/edit_spec.rb
  spec/features/merchant_items/index_spec.rb
  spec/features/merchant_items/new_spec.rb
  spec/features/merchant_items/show_spec.rb
  spec/features/merchants/dashboard_spec.rb
Labels: enhancement

#49 Setup to Main - initial set up finished
  app/views/merchant_items/edit.html.erb
  app/views/merchant_items/index.html.erb
  app/views/merchant_items/new.html.erb
  app/views/merchant_items/show.html.erb
  app/views/merchants/dashboard.html.erb
  config/routes.rb
  spec/features/merchant_items/edit_spec.rb
  spec/features/merchant_items/index_spec.rb
  spec/features/merchant_items/new_spec.rb
  spec/features/merchant_items/show_spec.rb
  spec/features/merchants/dashboard_spec.rb
Labels: enhancement, help wanted

#53 Us35
  app/controllers/merchant_items_controller.rb
  app/views/merchant_items/index.html.erb
  spec/features/merchant_items/index_spec.rb
Labels: enhancement

#54 Us39
  app/controllers/merchant_invoices_controller.rb
  app/views/merchant_dashboard/index.html.erb
  app/views/merchant_invoices/index.html.erb
  config/routes.rb
  spec/features/merchants/dashboard_spec.rb
Labels: enhancement

#56 Us38
  app/models/customer.rb
  app/models/invoice.rb
  app/models/invoice_item.rb
  app/models/item.rb
  app/models/merchant.rb
  app/models/transaction.rb
  app/views/merchant_dashboard/index.html.erb
  spec/features/merchant_items/show_spec.rb
  spec/features/merchants/dashboard_spec.rb
  spec/models/customer_spec.rb
  spec/models/invoice_item_spec.rb
  spec/models/invoice_spec.rb
  spec/models/item_spec.rb
  spec/models/merchant_spec.rb
  spec/models/transaction_spec.rb
Labels: enhancement, Advanced AR

#55 Us34
  app/controllers/merchant_items_controller.rb
  app/views/merchant_items/index.html.erb
  app/views/merchant_items/show.html.erb
  config/routes.rb
  spec/features/merchant_items/show_spec.rb
Labels: enhancement

#59 Us 37
  app/models/merchant.rb
  app/views/merchant_dashboard/index.html.erb
  config/routes.rb
  spec/features/merchants/dashboard_spec.rb
  spec/models/merchant_spec.rb
Labels: bug, ActiveRecord

#58 Feat: Updated routes references routes.rb
  app/controllers/merchant_items_controller.rb
  app/views/merchant_items/index.html.erb
  config/routes.rb
  spec/features/merchant_items/index_spec.rb
  spec/features/merchant_items/show_spec.rb
  spec/features/merchants/dashboard_spec.rb
Labels: enhancement

#60 Debug layout
  app/controllers/merchant_invoices_controller.rb
  app/views/layouts/application.html.erb
  app/views/merchant_dashboard/index.html.erb
  config/routes.rb
  spec/features/merchant_items/show_spec.rb
  spec/features/merchants/dashboard_spec.rb
Labels: enhancement

#61 Us33
  app/controllers/merchant_items_controller.rb
  app/views/merchant_items/edit.html.erb
  app/views/merchant_items/show.html.erb
  config/routes.rb
  spec/features/merchant_items/show_spec.rb
Labels: enhancement

#62 Us32
  .gitignore
  app/controllers/merchant_items_controller.rb
  app/models/item.rb
  app/views/merchant_items/index.html.erb
  config/routes.rb
  db/migrate/20220223215832_add_enabled_to_items.rb
  db/schema.rb
  spec/features/merchant_items/index_spec.rb
  spec/models/item_spec.rb
  spec/rails_helper.rb
Labels: enhancement

#67 Us30
  app/controllers/merchant_items_controller.rb
  app/views/merchant_items/index.html.erb
  app/views/merchant_items/new.html.erb
  spec/features/merchant_items/index_spec.rb
  spec/features/merchant_items/new_spec.rb
Labels: enhancement

#71 Us16
  app/controllers/admin/merchants_controller.rb
  app/views/admin/merchants/edit.html.erb
  app/views/admin/merchants/index.html.erb
  app/views/admin/merchants/show.html.erb
  spec/features/admin/merchants/show_spec.rb
Labels: enhancement
